const data = [
    {
      food: "apple",
      measurementUnit: "piece(s)",
      calories: 95,
      carbohydrates: 19.3,
      protein: 0.5,
      fat: 0.3,
    },
    {
      food: "banana",
      measurementUnit: "piece(s)",
      calories: 121,
      carbohydrates: 27.5,
      protein: 1.5,
      fat: 0.4,
    },
    {
      food: "egg",
      measurementUnit: "piece(s)",
      calories: 78,
      carbohydrates: 0.6,
      protein: 6.3,
      fat: 5.3,
    },
    {
      food: "white rice",
      measurementUnit: "grams",
      calories: 3.9,
      carbohydrates: 0.834,
      protein: 0.081,
      fat: 0.008,
    },
    {
      food: "sweet potato",
      measurementUnit: "piece(s)",
      calories: 135,
      carbohydrates: 26,
      protein: 3,
      fat: 0.2,
    },
    {
      food: "chicken breast",
      measurementUnit: "grams",
      calories: 1.21,
      carbohydrates: 0,
      protein: 0.216,
      fat: 0.032,
    },
    {
      food: "peanuts",
      measurementUnit: "grams",
      calories: 5.67,
      carbohydrates: 0.075,
      protein: 0.258,
      fat: 0.492,
    },
    {
      food: "kidney beans",
      measurementUnit: "grams",
      calories: 1.27,
      carbohydrates: 0.162,
      protein: 0.87,
      fat: 0.005,
    },
    {
      food: "tomatoes",
      measurementUnit: "piece(s)",
      calories: 22,
      carbohydrates: 3.2,
      protein: 1.1,
      fat: 0.2,
    },
    {
      food: "oatmeal",
      measurementUnit: "grams",
      calories: 3.79,
      carbohydrates: 0.576,
      protein: 0.132,
      fat: 0.065,
    },
    {
      food: "yogurt",
      measurementUnit: "grams",
      calories: 0.61,
      carbohydrates: 0.047,
      protein: 0.035,
      fat: 0.03,
    },
    {
      food: "cucumber",
      measurementUnit: "piece(s)",
      calories: 28,
      carbohydrates: 3.8,
      protein: 1.7,
      fat: 0.4,
    },
    {
      food: "orange",
      measurementUnit: "piece(s)",
      calories: 62,
      carbohydrates: 11.9,
      protein: 1.2,
      fat: 0.2,
    },
];

export default data